import { metaObject } from "@/config/site.config";

export const metadata = {
  ...metaObject(),
};

export default function FileDashboardPage({
  params: { lang },
}: {
  params: {
    lang: string;
  };
}) {
  return<>
  <div>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Consequatur nulla animi fugit voluptatibus iste, corporis officiis voluptas quos eveniet repudiandae doloremque repellendus totam, vel reprehenderit voluptatum ducimus magni, debitis architecto neque dolorem. Quam eaque fugiat voluptate quod blanditiis expedita reiciendis harum cumque. Esse accusantium saepe molestias eaque amet dolorum quia reprehenderit nam magni sunt nemo quis porro maiores, nostrum veritatis rerum dolore fugiat labore, mollitia ipsam! Repellat aut consequatur, nihil doloremque esse voluptatibus porro cupiditate obcaecati ad? Quisquam libero velit, accusantium veritatis eius nobis at corporis. Veniam, repellat esse iusto obcaecati dolores, enim assumenda nesciunt vero consectetur minus rem nam?</div>
  <div>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Consequatur nulla animi fugit voluptatibus iste, corporis officiis voluptas quos eveniet repudiandae doloremque repellendus totam, vel reprehenderit voluptatum ducimus magni, debitis architecto neque dolorem. Quam eaque fugiat voluptate quod blanditiis expedita reiciendis harum cumque. Esse accusantium saepe molestias eaque amet dolorum quia reprehenderit nam magni sunt nemo quis porro maiores, nostrum veritatis rerum dolore fugiat labore, mollitia ipsam! Repellat aut consequatur, nihil doloremque esse voluptatibus porro cupiditate obcaecati ad? Quisquam libero velit, accusantium veritatis eius nobis at corporis. Veniam, repellat esse iusto obcaecati dolores, enim assumenda nesciunt vero consectetur minus rem nam?</div>
  <div>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Consequatur nulla animi fugit voluptatibus iste, corporis officiis voluptas quos eveniet repudiandae doloremque repellendus totam, vel reprehenderit voluptatum ducimus magni, debitis architecto neque dolorem. Quam eaque fugiat voluptate quod blanditiis expedita reiciendis harum cumque. Esse accusantium saepe molestias eaque amet dolorum quia reprehenderit nam magni sunt nemo quis porro maiores, nostrum veritatis rerum dolore fugiat labore, mollitia ipsam! Repellat aut consequatur, nihil doloremque esse voluptatibus porro cupiditate obcaecati ad? Quisquam libero velit, accusantium veritatis eius nobis at corporis. Veniam, repellat esse iusto obcaecati dolores, enim assumenda nesciunt vero consectetur minus rem nam?</div>
  <div>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Consequatur nulla animi fugit voluptatibus iste, corporis officiis voluptas quos eveniet repudiandae doloremque repellendus totam, vel reprehenderit voluptatum ducimus magni, debitis architecto neque dolorem. Quam eaque fugiat voluptate quod blanditiis expedita reiciendis harum cumque. Esse accusantium saepe molestias eaque amet dolorum quia reprehenderit nam magni sunt nemo quis porro maiores, nostrum veritatis rerum dolore fugiat labore, mollitia ipsam! Repellat aut consequatur, nihil doloremque esse voluptatibus porro cupiditate obcaecati ad? Quisquam libero velit, accusantium veritatis eius nobis at corporis. Veniam, repellat esse iusto obcaecati dolores, enim assumenda nesciunt vero consectetur minus rem nam?</div>
  <div>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Consequatur nulla animi fugit voluptatibus iste, corporis officiis voluptas quos eveniet repudiandae doloremque repellendus totam, vel reprehenderit voluptatum ducimus magni, debitis architecto neque dolorem. Quam eaque fugiat voluptate quod blanditiis expedita reiciendis harum cumque. Esse accusantium saepe molestias eaque amet dolorum quia reprehenderit nam magni sunt nemo quis porro maiores, nostrum veritatis rerum dolore fugiat labore, mollitia ipsam! Repellat aut consequatur, nihil doloremque esse voluptatibus porro cupiditate obcaecati ad? Quisquam libero velit, accusantium veritatis eius nobis at corporis. Veniam, repellat esse iusto obcaecati dolores, enim assumenda nesciunt vero consectetur minus rem nam?</div>
  <div>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Consequatur nulla animi fugit voluptatibus iste, corporis officiis voluptas quos eveniet repudiandae doloremque repellendus totam, vel reprehenderit voluptatum ducimus magni, debitis architecto neque dolorem. Quam eaque fugiat voluptate quod blanditiis expedita reiciendis harum cumque. Esse accusantium saepe molestias eaque amet dolorum quia reprehenderit nam magni sunt nemo quis porro maiores, nostrum veritatis rerum dolore fugiat labore, mollitia ipsam! Repellat aut consequatur, nihil doloremque esse voluptatibus porro cupiditate obcaecati ad? Quisquam libero velit, accusantium veritatis eius nobis at corporis. Veniam, repellat esse iusto obcaecati dolores, enim assumenda nesciunt vero consectetur minus rem nam?</div>
  <div>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Consequatur nulla animi fugit voluptatibus iste, corporis officiis voluptas quos eveniet repudiandae doloremque repellendus totam, vel reprehenderit voluptatum ducimus magni, debitis architecto neque dolorem. Quam eaque fugiat voluptate quod blanditiis expedita reiciendis harum cumque. Esse accusantium saepe molestias eaque amet dolorum quia reprehenderit nam magni sunt nemo quis porro maiores, nostrum veritatis rerum dolore fugiat labore, mollitia ipsam! Repellat aut consequatur, nihil doloremque esse voluptatibus porro cupiditate obcaecati ad? Quisquam libero velit, accusantium veritatis eius nobis at corporis. Veniam, repellat esse iusto obcaecati dolores, enim assumenda nesciunt vero consectetur minus rem nam?</div>
  <div>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Consequatur nulla animi fugit voluptatibus iste, corporis officiis voluptas quos eveniet repudiandae doloremque repellendus totam, vel reprehenderit voluptatum ducimus magni, debitis architecto neque dolorem. Quam eaque fugiat voluptate quod blanditiis expedita reiciendis harum cumque. Esse accusantium saepe molestias eaque amet dolorum quia reprehenderit nam magni sunt nemo quis porro maiores, nostrum veritatis rerum dolore fugiat labore, mollitia ipsam! Repellat aut consequatur, nihil doloremque esse voluptatibus porro cupiditate obcaecati ad? Quisquam libero velit, accusantium veritatis eius nobis at corporis. Veniam, repellat esse iusto obcaecati dolores, enim assumenda nesciunt vero consectetur minus rem nam?</div>
  <div>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Consequatur nulla animi fugit voluptatibus iste, corporis officiis voluptas quos eveniet repudiandae doloremque repellendus totam, vel reprehenderit voluptatum ducimus magni, debitis architecto neque dolorem. Quam eaque fugiat voluptate quod blanditiis expedita reiciendis harum cumque. Esse accusantium saepe molestias eaque amet dolorum quia reprehenderit nam magni sunt nemo quis porro maiores, nostrum veritatis rerum dolore fugiat labore, mollitia ipsam! Repellat aut consequatur, nihil doloremque esse voluptatibus porro cupiditate obcaecati ad? Quisquam libero velit, accusantium veritatis eius nobis at corporis. Veniam, repellat esse iusto obcaecati dolores, enim assumenda nesciunt vero consectetur minus rem nam?</div>
  <div>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Consequatur nulla animi fugit voluptatibus iste, corporis officiis voluptas quos eveniet repudiandae doloremque repellendus totam, vel reprehenderit voluptatum ducimus magni, debitis architecto neque dolorem. Quam eaque fugiat voluptate quod blanditiis expedita reiciendis harum cumque. Esse accusantium saepe molestias eaque amet dolorum quia reprehenderit nam magni sunt nemo quis porro maiores, nostrum veritatis rerum dolore fugiat labore, mollitia ipsam! Repellat aut consequatur, nihil doloremque esse voluptatibus porro cupiditate obcaecati ad? Quisquam libero velit, accusantium veritatis eius nobis at corporis. Veniam, repellat esse iusto obcaecati dolores, enim assumenda nesciunt vero consectetur minus rem nam?</div>
  <div>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Consequatur nulla animi fugit voluptatibus iste, corporis officiis voluptas quos eveniet repudiandae doloremque repellendus totam, vel reprehenderit voluptatum ducimus magni, debitis architecto neque dolorem. Quam eaque fugiat voluptate quod blanditiis expedita reiciendis harum cumque. Esse accusantium saepe molestias eaque amet dolorum quia reprehenderit nam magni sunt nemo quis porro maiores, nostrum veritatis rerum dolore fugiat labore, mollitia ipsam! Repellat aut consequatur, nihil doloremque esse voluptatibus porro cupiditate obcaecati ad? Quisquam libero velit, accusantium veritatis eius nobis at corporis. Veniam, repellat esse iusto obcaecati dolores, enim assumenda nesciunt vero consectetur minus rem nam?</div>
  <div>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Consequatur nulla animi fugit voluptatibus iste, corporis officiis voluptas quos eveniet repudiandae doloremque repellendus totam, vel reprehenderit voluptatum ducimus magni, debitis architecto neque dolorem. Quam eaque fugiat voluptate quod blanditiis expedita reiciendis harum cumque. Esse accusantium saepe molestias eaque amet dolorum quia reprehenderit nam magni sunt nemo quis porro maiores, nostrum veritatis rerum dolore fugiat labore, mollitia ipsam! Repellat aut consequatur, nihil doloremque esse voluptatibus porro cupiditate obcaecati ad? Quisquam libero velit, accusantium veritatis eius nobis at corporis. Veniam, repellat esse iusto obcaecati dolores, enim assumenda nesciunt vero consectetur minus rem nam?</div>
  <div>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Consequatur nulla animi fugit voluptatibus iste, corporis officiis voluptas quos eveniet repudiandae doloremque repellendus totam, vel reprehenderit voluptatum ducimus magni, debitis architecto neque dolorem. Quam eaque fugiat voluptate quod blanditiis expedita reiciendis harum cumque. Esse accusantium saepe molestias eaque amet dolorum quia reprehenderit nam magni sunt nemo quis porro maiores, nostrum veritatis rerum dolore fugiat labore, mollitia ipsam! Repellat aut consequatur, nihil doloremque esse voluptatibus porro cupiditate obcaecati ad? Quisquam libero velit, accusantium veritatis eius nobis at corporis. Veniam, repellat esse iusto obcaecati dolores, enim assumenda nesciunt vero consectetur minus rem nam?</div>
  <div>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Consequatur nulla animi fugit voluptatibus iste, corporis officiis voluptas quos eveniet repudiandae doloremque repellendus totam, vel reprehenderit voluptatum ducimus magni, debitis architecto neque dolorem. Quam eaque fugiat voluptate quod blanditiis expedita reiciendis harum cumque. Esse accusantium saepe molestias eaque amet dolorum quia reprehenderit nam magni sunt nemo quis porro maiores, nostrum veritatis rerum dolore fugiat labore, mollitia ipsam! Repellat aut consequatur, nihil doloremque esse voluptatibus porro cupiditate obcaecati ad? Quisquam libero velit, accusantium veritatis eius nobis at corporis. Veniam, repellat esse iusto obcaecati dolores, enim assumenda nesciunt vero consectetur minus rem nam?</div>
  
  </>
}
